const off = {
    aut_datos: '2',
    backupconsciudad: '',
    barrio: '',
    checkbox_aut_datos: 'on',
    cliente: 'deudor',
    codcob_dir: '2',
    complemento1: '',
    complemento2: '',
    complemento3: '',
    consciudad: '',
    consdocdeu: '759703',
    consrefer: '',
    depto: '',
    despues_submit: 'frmResponseGeneric',
    escorrespondencia: '2',
    formato_info: 'SIIF',
    fuente_cambio: 'Adminfo',
    letraOff1: '',
    letraOff2: '',
    nit: '1239488313',
    nom_programa: 'listadireccion',
    numeroOff1: '',
    numeroOff2: '',
    numeroOff3: '',
    numeroOff4: '',
    numeroOff5: '',
    prioridad: '2',
    s2id_autogen15: '',
    s2id_autogen16: '',
    s2id_autogen17: '',
    s2id_autogen18: '',
    s2id_autogen19: '',
    s2id_autogen20: '',
    s2id_autogen21: '',
    s2id_autogen22: '',
    s2id_autogen23: '',
}

Object.keys(off).forEach(item => off[item] == '' && delete off[item])
console.log(off)